// Quellenkatalog — die einzige Stelle, an der Quellen gepflegt werden.
//
// Aus ihm speisen sich die Auswahl „Bevorzugte Quellen" in der Anwendung, der
// Quellenabschnitt im Prompt UND die Durchsichtsbögen für die Dozenten
// (quellen-durchsicht/erzeugen.mjs). Wer hier etwas ändert, ändert alles
// gleichzeitig — so können App und Bögen nicht auseinanderlaufen.
//
// Stand September 2026: Die Dozenten haben kaum geantwortet. Übernommen ist deshalb
// die eigene Vorauswahl, abgeglichen mit den Rahmenlehrplänen aller 14 Berufe.
// Sie ist ausdrücklich vorläufig und wird nachgebessert, sobald Rückmeldungen
// kommen (Issue #1).
//
// Zwei Regeln:
//
// 1. Hier stehen nur zitierfähige Quellen. Themen, zu denen die Dozenten ihr
//    Lehrwerk nennen sollen ("Handelskalkulation"), stehen nur im Bogen
//    (quellen-durchsicht/durchsicht.mjs) — im Prompt wäre "Belege aus:
//    Handelskalkulation" sinnlos.
// 2. Bezeichner sind stabil. Wer eine Quelle ausgewählt hat, behält sie über
//    jede Änderung des Katalogs hinweg; bisherige Bezeichner wurden
//    übernommen.
//
// Hinweise an die Dozenten stehen bewusst NICHT hier, sondern in
// quellen-durchsicht/durchsicht.mjs, verknüpft über den Bezeichner. So
// gelangen sie nicht einmal ins ausgelieferte Programm — rund ein Drittel
// der Datenmenge, die jedes Telefon sonst ungesehen mitlüde.
//
// Diese Datei darf zur Laufzeit nur Typen importieren: Der Bogen-Erzeuger
// lädt sie direkt mit Node, ohne Übersetzungsschritt.

import type { BerufId } from './types';

export type QuellenArt =
  | 'vorgabe'
  | 'gesetz'
  | 'norm'
  | 'nachschlagewerk'
  | 'rechtsprechung'
  | 'daten';

export interface KatalogQuelle {
  /** Stabiler Bezeichner; so wird die Auswahl gespeichert. */
  id: string;
  /** Kurzbezeichnung in der Auswahlliste. */
  kuerzel: string;
  /** Erläuterung in der Auswahlliste. */
  titel: string;
  art: QuellenArt;
  /** Fehlt die Angabe, gilt die Quelle für alle Berufe. */
  berufe?: BerufId[];
  /** Beim ersten Start und bei „Auf Standard" angehakt. */
  standard?: boolean;
  /** Wortlaut im Prompt, wenn „Kürzel (Titel)" dort nicht taugt. */
  prompt?: string;
}

export const KATALOG: KatalogQuelle[] = [
  {
    id: 'bgb',
    kuerzel: 'BGB',
    titel: 'Bürgerliches Gesetzbuch',
    art: 'gesetz',
  },
  {
    id: 'hgb',
    kuerzel: 'HGB',
    titel: 'Handelsgesetzbuch',
    art: 'gesetz',
  },
  {
    id: 'gewo',
    kuerzel: 'GewO',
    titel: 'Gewerbeordnung',
    art: 'gesetz',
  },
  {
    id: 'uwg',
    kuerzel: 'UWG',
    titel: 'Gesetz gegen den unlauteren Wettbewerb',
    art: 'gesetz',
  },
  {
    id: 'prodhaftg',
    kuerzel: 'ProdHaftG',
    titel: 'Produkthaftungsgesetz',
    art: 'gesetz',
  },
  {
    id: 'zpo',
    kuerzel: 'ZPO',
    titel: 'Zivilprozessordnung',
    art: 'gesetz',
  },
  {
    id: 'inso',
    kuerzel: 'InsO',
    titel: 'Insolvenzordnung',
    art: 'gesetz',
  },
  {
    id: 'gmbhg-aktg',
    kuerzel: 'GmbHG / AktG',
    titel: 'GmbH-Gesetz und Aktiengesetz',
    art: 'gesetz',
  },
  {
    id: 'bbig',
    kuerzel: 'BBiG',
    titel: 'Berufsbildungsgesetz',
    art: 'gesetz',
  },
  {
    id: 'jarbschg',
    kuerzel: 'JArbSchG',
    titel: 'Jugendarbeitsschutzgesetz',
    art: 'gesetz',
  },
  {
    id: 'arbzg',
    kuerzel: 'ArbZG',
    titel: 'Arbeitszeitgesetz',
    art: 'gesetz',
  },
  {
    id: 'burlg',
    kuerzel: 'BUrlG',
    titel: 'Bundesurlaubsgesetz',
    art: 'gesetz',
  },
  {
    id: 'entgfg',
    kuerzel: 'EntgFG',
    titel: 'Entgeltfortzahlungsgesetz',
    art: 'gesetz',
  },
  {
    id: 'kschg',
    kuerzel: 'KSchG',
    titel: 'Kündigungsschutzgesetz',
    art: 'gesetz',
  },
  {
    id: 'tzbfg',
    kuerzel: 'TzBfG',
    titel: 'Teilzeit- und Befristungsgesetz',
    art: 'gesetz',
  },
  {
    id: 'betrvg',
    kuerzel: 'BetrVG',
    titel: 'Betriebsverfassungsgesetz',
    art: 'gesetz',
  },
  {
    id: 'tvg',
    kuerzel: 'TVG',
    titel: 'Tarifvertragsgesetz',
    art: 'gesetz',
  },
  {
    id: 'milog',
    kuerzel: 'MiLoG',
    titel: 'Mindestlohngesetz',
    art: 'gesetz',
  },
  {
    id: 'agg',
    kuerzel: 'AGG',
    titel: 'Allgemeines Gleichbehandlungsgesetz',
    art: 'gesetz',
  },
  {
    id: 'muschg-beeg',
    kuerzel: 'MuSchG / BEEG',
    titel: 'Mutterschutzgesetz, Bundeselterngeld- und Elternzeitgesetz',
    art: 'gesetz',
  },
  {
    id: 'arbschg',
    kuerzel: 'ArbSchG',
    titel: 'Arbeitsschutzgesetz',
    art: 'gesetz',
  },
  {
    id: 'sgb-iii-xi',
    kuerzel: 'SGB III–XI',
    titel: 'Sozialgesetzbuch',
    art: 'gesetz',
  },
  {
    id: 'ustg',
    kuerzel: 'UStG',
    titel: 'Umsatzsteuergesetz',
    art: 'gesetz',
  },
  {
    id: 'estg',
    kuerzel: 'EStG',
    titel: 'Einkommensteuergesetz',
    art: 'gesetz',
  },
  {
    id: 'ao',
    kuerzel: 'AO',
    titel: 'Abgabenordnung',
    art: 'gesetz',
  },
  {
    id: 'gobd',
    kuerzel: 'GoBD',
    titel: 'Grundsätze ordnungsmäßiger Buchführung in elektronischer Form',
    art: 'gesetz',
  },
  {
    id: 'dsgvo',
    kuerzel: 'DSGVO / BDSG',
    titel: 'Datenschutz-Grundverordnung und Bundesdatenschutzgesetz',
    art: 'gesetz',
  },
  {
    id: 'pruefungsordnung',
    kuerzel: 'Prüfungsordnung',
    titel: 'Prüfungsordnung der zuständigen Kammer',
    art: 'vorgabe',
    prompt: 'Prüfungsordnung der zuständigen Kammer',
  },
  {
    id: 'aka',
    kuerzel: 'AkA',
    titel: 'AkA-Prüfungskataloge',
    art: 'vorgabe',
  },
  {
    id: 'ihk-veroeffentlichungen',
    kuerzel: 'IHK-Merkblätter',
    titel: 'Merkblätter und Veröffentlichungen der zuständigen IHK',
    art: 'vorgabe',
    prompt: 'Merkblätter der zuständigen IHK',
  },
  {
    id: 'dihk',
    kuerzel: 'DIHK',
    titel: 'DIHK-Materialien und Umsetzungshilfen',
    art: 'vorgabe',
  },
  {
    id: 'gesetze-im-internet-de',
    kuerzel: 'gesetze-im-internet.de',
    titel: 'Amtliche Gesetzesfassungen des Bundes',
    art: 'nachschlagewerk',
    standard: true,
  },
  {
    id: 'recht-nrw-de',
    kuerzel: 'recht.nrw.de',
    titel: 'Landesrecht Nordrhein-Westfalen',
    art: 'nachschlagewerk',
  },
  {
    id: 'eur-lex',
    kuerzel: 'EUR-Lex',
    titel: 'Amtliches Portal des EU-Rechts',
    art: 'nachschlagewerk',
  },
  {
    id: 'gabler',
    kuerzel: 'Gabler',
    titel: 'Springer Gabler Wirtschaftslexikon',
    art: 'nachschlagewerk',
    standard: true,
  },
  {
    id: 'haufe',
    kuerzel: 'Haufe',
    titel: 'Haufe Fachdatenbank',
    art: 'nachschlagewerk',
  },
  {
    id: 'nwb',
    kuerzel: 'NWB',
    titel: 'NWB Verlag',
    art: 'nachschlagewerk',
  },
  {
    id: 'destatis',
    kuerzel: 'Destatis',
    titel: 'Statistisches Bundesamt',
    art: 'daten',
  },
  {
    id: 'it-nrw',
    kuerzel: 'IT.NRW',
    titel: 'Statistisches Landesamt Nordrhein-Westfalen',
    art: 'daten',
  },
  {
    id: 'bundesbank',
    kuerzel: 'Bundesbank',
    titel: 'Deutsche Bundesbank',
    art: 'daten',
  },
  {
    id: 'bag',
    kuerzel: 'BAG',
    titel: 'Bundesarbeitsgericht',
    art: 'rechtsprechung',
  },
  {
    id: 'bgh',
    kuerzel: 'BGH',
    titel: 'Bundesgerichtshof',
    art: 'rechtsprechung',
  },
  {
    id: 'eugh',
    kuerzel: 'EuGH',
    titel: 'Gerichtshof der Europäischen Union',
    art: 'rechtsprechung',
  },
  {
    id: 'kmk-qualifikationsprofil-wiso',
    kuerzel: 'KMK-Qualifikationsprofil WiSo',
    titel: 'Kompetenzorientiertes Qualifikationsprofil Wirtschafts- und Sozialkunde',
    art: 'vorgabe',
    berufe: ['kgq'],
    standard: true,
    prompt: 'Kompetenzorientiertes Qualifikationsprofil Wirtschafts- und Sozialkunde der KMK (2021)',
  },
  {
    id: 'aka-katalog-wiso',
    kuerzel: 'AkA-Katalog WiSo',
    titel: 'Prüfungskatalog Wirtschafts- und Sozialkunde',
    art: 'vorgabe',
    berufe: ['kgq'],
    standard: true,
    prompt: 'Prüfungskatalog Wirtschafts- und Sozialkunde der AkA',
  },
  {
    id: 'gg',
    kuerzel: 'GG',
    titel: 'Grundgesetz',
    art: 'gesetz',
    berufe: ['kgq'],
  },
  {
    id: 'drv-gkv',
    kuerzel: 'DRV / GKV',
    titel: 'Deutsche Rentenversicherung und Krankenkassen',
    art: 'nachschlagewerk',
    berufe: ['kgq'],
  },
  {
    id: 'vvg',
    kuerzel: 'VVG',
    titel: 'Versicherungsvertragsgesetz',
    art: 'gesetz',
    berufe: ['kgq'],
  },
  {
    id: 'verbraucherzentrale-nrw',
    kuerzel: 'Verbraucherzentrale NRW',
    titel: 'Verbraucherinformation und Musterschreiben',
    art: 'nachschlagewerk',
    berufe: ['kgq'],
  },
  {
    id: 'bpb',
    kuerzel: 'bpb',
    titel: 'Bundeszentrale für politische Bildung',
    art: 'nachschlagewerk',
    berufe: ['kgq'],
  },
  {
    id: 'europa-eu',
    kuerzel: 'europa.eu',
    titel: 'Institutionen der Europäischen Union',
    art: 'nachschlagewerk',
    berufe: ['kgq'],
  },
  {
    id: 'existenzgruendung',
    kuerzel: 'Existenzgründung',
    titel: 'Gründungsinformationen der IHK und des BMWK',
    art: 'nachschlagewerk',
    berufe: ['kgq'],
    prompt: 'Gründungsinformationen der IHK und des Bundeswirtschaftsministeriums',
  },
  {
    id: 'berufenet',
    kuerzel: 'BERUFENET',
    titel: 'Berufsinformationen der Bundesagentur für Arbeit',
    art: 'daten',
    berufe: ['kgq'],
  },
  {
    id: 'ao-einzelhandel',
    kuerzel: 'Ausbildungsordnung',
    titel: 'Verordnung über die Berufsausbildung im Einzelhandel',
    art: 'vorgabe',
    berufe: ['einzelhandel'],
    standard: true,
    prompt: 'Verordnung über die Berufsausbildung im Einzelhandel',
  },
  {
    id: 'rahmenlehrplan-ehk',
    kuerzel: 'Rahmenlehrplan',
    titel: 'Vierzehn Lernfelder, 880 Stunden',
    art: 'vorgabe',
    berufe: ['einzelhandel'],
    standard: true,
    prompt: 'Rahmenlehrplan der KMK für Kaufleute im Einzelhandel',
  },
  {
    id: 'kassensichv-par-146a-ao',
    kuerzel: 'KassenSichV / § 146a AO',
    titel: 'Ordnungsmäßigkeit der Kassenführung',
    art: 'gesetz',
    berufe: ['einzelhandel'],
  },
  {
    id: 'hgb-par-240-f',
    kuerzel: 'HGB §§ 240 f.',
    titel: 'Inventur und Inventar',
    art: 'gesetz',
    berufe: ['einzelhandel'],
  },
  {
    id: 'loeg-nrw',
    kuerzel: 'LÖG NRW',
    titel: 'Ladenöffnungsgesetz Nordrhein-Westfalen',
    art: 'gesetz',
    berufe: ['einzelhandel'],
  },
  {
    id: 'pangv',
    kuerzel: 'PAngV',
    titel: 'Preisangabenverordnung',
    art: 'gesetz',
    berufe: ['einzelhandel', 'ecommerce'],
  },
  {
    id: 'juschg',
    kuerzel: 'JuSchG',
    titel: 'Jugendschutzgesetz',
    art: 'gesetz',
    berufe: ['einzelhandel'],
  },
  {
    id: 'lfgb',
    kuerzel: 'LFGB',
    titel: 'Lebensmittel- und Futtermittelgesetzbuch',
    art: 'gesetz',
    berufe: ['einzelhandel'],
  },
  {
    id: 'lmiv',
    kuerzel: 'LMIV',
    titel: 'EU-Lebensmittelinformationsverordnung 1169/2011',
    art: 'gesetz',
    berufe: ['einzelhandel'],
  },
  {
    id: 'messeg-messev',
    kuerzel: 'MessEG / MessEV',
    titel: 'Mess- und Eichgesetz mit Verordnung',
    art: 'gesetz',
    berufe: ['einzelhandel'],
  },
  {
    id: 'verpackg',
    kuerzel: 'VerpackG',
    titel: 'Verpackungsgesetz',
    art: 'gesetz',
    berufe: ['einzelhandel', 'lagerlogistik'],
  },
  {
    id: 'gpsr',
    kuerzel: 'GPSR',
    titel: 'EU-Produktsicherheitsverordnung 2023/988',
    art: 'gesetz',
    berufe: ['einzelhandel'],
  },
  {
    id: 'bgb-fernabsatz',
    kuerzel: 'BGB §§ 312 ff.',
    titel: 'Fernabsatz und Widerruf, §§ 312 ff., § 355 BGB',
    art: 'gesetz',
    berufe: ['einzelhandel', 'ecommerce'],
    prompt: 'BGB §§ 312 ff. und § 355 (Fernabsatz und Widerruf)',
  },
  {
    id: 'hde',
    kuerzel: 'HDE',
    titel: 'Handelsverband Deutschland',
    art: 'daten',
    berufe: ['einzelhandel'],
  },
  {
    id: 'ehi',
    kuerzel: 'EHI',
    titel: 'EHI Retail Institute',
    art: 'daten',
    berufe: ['einzelhandel'],
  },
  {
    id: 'ao-it-berufe',
    kuerzel: 'Ausbildungsordnung',
    titel: 'Verordnung über die Berufsausbildung in den IT-Berufen',
    art: 'vorgabe',
    berufe: ['fachinformatik'],
    standard: true,
    prompt: 'Verordnung über die Berufsausbildung in den IT-Berufen',
  },
  {
    id: 'rahmenlehrplan-it-2020',
    kuerzel: 'Rahmenlehrplan',
    titel: 'Zwölf Lernfelder, davon 1 bis 9 gemeinsam',
    art: 'vorgabe',
    berufe: ['fachinformatik'],
    standard: true,
    prompt: 'Rahmenlehrplan der KMK für Fachinformatiker – Systemintegration',
  },
  {
    id: 'bgb-par-611-631',
    kuerzel: 'BGB §§ 611, 631',
    titel: 'Dienstvertrag und Werkvertrag',
    art: 'gesetz',
    berufe: ['fachinformatik'],
  },
  {
    id: 'bfsg-bitv-2-0',
    kuerzel: 'BFSG / BITV 2.0',
    titel: 'Barrierefreiheitsstärkungsgesetz und Barrierefreie-IT-Verordnung',
    art: 'gesetz',
    berufe: ['fachinformatik'],
  },
  {
    id: 'arbstaettv-anhang-6',
    kuerzel: 'ArbStättV Anhang 6',
    titel: 'Bildschirmarbeitsplätze',
    art: 'gesetz',
    berufe: ['fachinformatik'],
  },
  {
    id: 'urhg',
    kuerzel: 'UrhG',
    titel: 'Urheberrechtsgesetz',
    art: 'gesetz',
    berufe: ['fachinformatik'],
  },
  {
    id: 'stgb-par-202a-ff',
    kuerzel: 'StGB §§ 202a ff.',
    titel: 'Computerstrafrecht',
    art: 'gesetz',
    berufe: ['fachinformatik'],
  },
  {
    id: 'bsig-nis2',
    kuerzel: 'BSIG / NIS2',
    titel: 'BSI-Gesetz und NIS-2-Umsetzung',
    art: 'gesetz',
    berufe: ['fachinformatik'],
  },
  {
    id: 'tkg',
    kuerzel: 'TKG',
    titel: 'Telekommunikationsgesetz',
    art: 'gesetz',
    berufe: ['fachinformatik'],
  },
  {
    id: 'tdddg',
    kuerzel: 'TDDDG',
    titel: 'Telekommunikation-Digitale-Dienste-Datenschutz-Gesetz',
    art: 'gesetz',
    berufe: ['fachinformatik'],
  },
  {
    id: 'ki-vo',
    kuerzel: 'KI-VO',
    titel: 'EU-Verordnung über künstliche Intelligenz 2024/1689',
    art: 'gesetz',
    berufe: ['fachinformatik'],
  },
  {
    id: 'bsi',
    kuerzel: 'IT-Grundschutz',
    titel: 'BSI IT-Grundschutz-Kompendium',
    art: 'norm',
    berufe: ['fachinformatik'],
  },
  {
    id: 'iso-iec-27001',
    kuerzel: 'ISO/IEC 27001',
    titel: 'Informationssicherheits-Managementsysteme',
    art: 'norm',
    berufe: ['fachinformatik'],
  },
  {
    id: 'itil',
    kuerzel: 'ITIL',
    titel: 'IT-Service-Management nach ITIL',
    art: 'norm',
    berufe: ['fachinformatik'],
  },
  {
    id: 'ieee-802',
    kuerzel: 'IEEE 802',
    titel: 'Netzwerkstandards',
    art: 'norm',
    berufe: ['fachinformatik'],
  },
  {
    id: 'rfc',
    kuerzel: 'RFC',
    titel: 'Requests for Comments der IETF',
    art: 'norm',
    berufe: ['fachinformatik'],
  },
  {
    id: 'din-en-iso-9241',
    kuerzel: 'DIN EN ISO 9241',
    titel: 'Ergonomie der Mensch-System-Interaktion',
    art: 'norm',
    berufe: ['fachinformatik'],
  },
  {
    id: 'herstellerdoku',
    kuerzel: 'Herstellerdoku',
    titel: 'Microsoft Learn, Cisco, Linux-Handbücher',
    art: 'nachschlagewerk',
    berufe: ['fachinformatik'],
  },
  {
    id: 'c-t-ix',
    kuerzel: 'c\'t / iX',
    titel: 'Heise-Fachpresse',
    art: 'nachschlagewerk',
    berufe: ['fachinformatik'],
  },
  {
    id: 'ao-lagerlogistik',
    kuerzel: 'Ausbildungsordnung',
    titel: 'Verordnung über die Berufsausbildung zur Fachkraft für Lagerlogistik',
    art: 'vorgabe',
    berufe: ['lagerlogistik'],
    standard: true,
    prompt: 'Verordnung über die Berufsausbildung zur Fachkraft für Lagerlogistik',
  },
  {
    id: 'rahmenlehrplan-fkl',
    kuerzel: 'Rahmenlehrplan',
    titel: 'Zwölf Lernfelder, 840 Stunden',
    art: 'vorgabe',
    berufe: ['lagerlogistik'],
    standard: true,
    prompt: 'Rahmenlehrplan der KMK für Fachkräfte für Lagerlogistik',
  },
  {
    id: 'vo-eg-561-2006',
    kuerzel: 'VO (EG) 561/2006',
    titel: 'Lenk- und Ruhezeiten',
    art: 'gesetz',
    berufe: ['lagerlogistik', 'spedition'],
  },
  {
    id: 'hgb-par-407-ff-cmr',
    kuerzel: 'HGB §§ 407 ff. / CMR',
    titel: 'Frachtrecht und Frachtpapiere',
    art: 'gesetz',
    berufe: ['lagerlogistik', 'grosshandel'],
  },
  {
    id: 'dguv-vorschrift-68',
    kuerzel: 'DGUV Vorschrift 68',
    titel: 'Flurförderzeuge',
    art: 'norm',
    berufe: ['lagerlogistik'],
  },
  {
    id: 'dguv-grundsatz-308-001',
    kuerzel: 'DGUV Grundsatz 308-001',
    titel: 'Ausbildung von Fahrpersonal für Flurförderzeuge',
    art: 'norm',
    berufe: ['lagerlogistik'],
  },
  {
    id: 'betrsichv',
    kuerzel: 'BetrSichV',
    titel: 'Betriebssicherheitsverordnung',
    art: 'gesetz',
    berufe: ['lagerlogistik'],
  },
  {
    id: 'arbstaettv',
    kuerzel: 'ArbStättV',
    titel: 'Arbeitsstättenverordnung',
    art: 'gesetz',
    berufe: ['lagerlogistik', 'bueromanagement'],
  },
  {
    id: 'lasthandhabv',
    kuerzel: 'LasthandhabV',
    titel: 'Lastenhandhabungsverordnung',
    art: 'gesetz',
    berufe: ['lagerlogistik'],
  },
  {
    id: 'gefstoffv',
    kuerzel: 'GefStoffV',
    titel: 'Gefahrstoffverordnung',
    art: 'gesetz',
    berufe: ['lagerlogistik'],
  },
  {
    id: 'trgs-510',
    kuerzel: 'TRGS 510',
    titel: 'Lagerung von Gefahrstoffen in ortsbeweglichen Behältern',
    art: 'norm',
    berufe: ['lagerlogistik'],
  },
  {
    id: 'gefahrgut',
    kuerzel: 'GGVSEB / ADR',
    titel: 'Gefahrgutverordnung Straße, Eisenbahn, Binnenschiff',
    art: 'gesetz',
    berufe: ['lagerlogistik', 'spedition'],
  },
  {
    id: 'stvo-par-22',
    kuerzel: 'StVO § 22',
    titel: 'Ladung und Ladungssicherung',
    art: 'gesetz',
    berufe: ['lagerlogistik'],
  },
  {
    id: 'vdi-2700',
    kuerzel: 'VDI 2700',
    titel: 'Ladungssicherung auf Straßenfahrzeugen',
    art: 'norm',
    berufe: ['lagerlogistik'],
  },
  {
    id: 'hgb-par-467-ff',
    kuerzel: 'HGB §§ 467 ff.',
    titel: 'Lagergeschäft',
    art: 'gesetz',
    berufe: ['lagerlogistik'],
  },
  {
    id: 'epal-din-en-13698',
    kuerzel: 'EPAL / DIN EN 13698',
    titel: 'Europalette und Palettentausch',
    art: 'norm',
    berufe: ['lagerlogistik'],
  },
  {
    id: 'lmhv',
    kuerzel: 'LMHV',
    titel: 'Lebensmittelhygiene-Verordnung',
    art: 'gesetz',
    berufe: ['lagerlogistik'],
  },
  {
    id: 'ao-schutz-und-sicherheit',
    kuerzel: 'Ausbildungsordnung',
    titel: 'Verordnung über die Berufsausbildung zur Fachkraft für Schutz und Sicherheit',
    art: 'vorgabe',
    berufe: ['schutzsicherheit'],
    standard: true,
    prompt: 'Verordnung über die Berufsausbildung zur Fachkraft für Schutz und Sicherheit',
  },
  {
    id: 'rahmenlehrplan-fks',
    kuerzel: 'Rahmenlehrplan',
    titel: 'Zwölf Lernfelder, KMK-Beschluss vom 10.04.2008',
    art: 'vorgabe',
    berufe: ['schutzsicherheit'],
    standard: true,
    prompt: 'Rahmenlehrplan der KMK für Fachkräfte für Schutz und Sicherheit',
  },
  {
    id: 'owig',
    kuerzel: 'OWiG',
    titel: 'Gesetz über Ordnungswidrigkeiten',
    art: 'gesetz',
    berufe: ['schutzsicherheit'],
  },
  {
    id: 'dguv-vorschrift-1',
    kuerzel: 'DGUV Vorschrift 1',
    titel: 'Grundsätze der Prävention',
    art: 'norm',
    berufe: ['schutzsicherheit'],
  },
  {
    id: 'gewo-par-34a',
    kuerzel: 'GewO § 34a',
    titel: 'Bewachungsgewerbe',
    art: 'gesetz',
    berufe: ['schutzsicherheit'],
  },
  {
    id: 'bewachv',
    kuerzel: 'BewachV',
    titel: 'Bewachungsverordnung',
    art: 'gesetz',
    berufe: ['schutzsicherheit'],
  },
  {
    id: 'stgb',
    kuerzel: 'StGB',
    titel: 'Strafgesetzbuch',
    art: 'gesetz',
    berufe: ['schutzsicherheit'],
  },
  {
    id: 'stpo',
    kuerzel: 'StPO § 127',
    titel: 'Vorläufige Festnahme (Jedermannsrecht)',
    art: 'gesetz',
    berufe: ['schutzsicherheit'],
  },
  {
    id: 'bgb-par-227-ff',
    kuerzel: 'BGB §§ 227 ff.',
    titel: 'Notwehr, Selbsthilfe, Besitzwehr § 859',
    art: 'gesetz',
    berufe: ['schutzsicherheit'],
  },
  {
    id: 'bgb-par-903-1004',
    kuerzel: 'BGB §§ 903, 1004',
    titel: 'Eigentum und Hausrecht',
    art: 'gesetz',
    berufe: ['schutzsicherheit'],
  },
  {
    id: 'waffg',
    kuerzel: 'WaffG',
    titel: 'Waffengesetz',
    art: 'gesetz',
    berufe: ['schutzsicherheit'],
  },
  {
    id: 'bdsg-par-4',
    kuerzel: 'BDSG § 4',
    titel: 'Videoüberwachung öffentlich zugänglicher Räume',
    art: 'gesetz',
    berufe: ['schutzsicherheit'],
  },
  {
    id: 'dguv-vorschrift-23',
    kuerzel: 'DGUV Vorschrift 23',
    titel: 'Wach- und Sicherungsdienste',
    art: 'norm',
    berufe: ['schutzsicherheit'],
  },
  {
    id: 'din-77200',
    kuerzel: 'DIN 77200',
    titel: 'Anforderungen an Sicherungsdienstleistungen',
    art: 'norm',
    berufe: ['schutzsicherheit'],
  },
  {
    id: 'din-14096',
    kuerzel: 'DIN 14096',
    titel: 'Brandschutzordnung Teil A, B, C',
    art: 'norm',
    berufe: ['schutzsicherheit'],
  },
  {
    id: 'bhkg-nrw',
    kuerzel: 'BHKG NRW',
    titel: 'Gesetz über den Brandschutz, die Hilfeleistung und den Katastrophenschutz',
    art: 'gesetz',
    berufe: ['schutzsicherheit'],
  },
  {
    id: 'vds-richtlinien',
    kuerzel: 'VdS-Richtlinien',
    titel: 'VdS Schadenverhütung',
    art: 'norm',
    berufe: ['schutzsicherheit'],
  },
  {
    id: 'luftsig',
    kuerzel: 'LuftSiG',
    titel: 'Luftsicherheitsgesetz',
    art: 'gesetz',
    berufe: ['schutzsicherheit'],
  },
  {
    id: 'ao-gross-und-aussenhandel',
    kuerzel: 'Ausbildungsordnung',
    titel: 'Verordnung über die Berufsausbildung im Groß- und Außenhandelsmanagement',
    art: 'vorgabe',
    berufe: ['grosshandel'],
    standard: true,
    prompt: 'Verordnung über die Berufsausbildung im Groß- und Außenhandelsmanagement',
  },
  {
    id: 'rahmenlehrplan-gam-2020',
    kuerzel: 'Rahmenlehrplan',
    titel: 'Dreizehn Lernfelder, ab dem dritten Jahr nach Fachrichtung getrennt',
    art: 'vorgabe',
    berufe: ['grosshandel'],
    standard: true,
    prompt: 'Rahmenlehrplan der KMK für Kaufleute im Groß- und Außenhandelsmanagement',
  },
  {
    id: 'hgb-par-373-ff',
    kuerzel: 'HGB §§ 373 ff.',
    titel: 'Handelskauf',
    art: 'gesetz',
    berufe: ['grosshandel'],
  },
  {
    id: 'cisg',
    kuerzel: 'CISG',
    titel: 'UN-Kaufrecht',
    art: 'gesetz',
    berufe: ['grosshandel'],
  },
  {
    id: 'incoterms',
    kuerzel: 'Incoterms 2020',
    titel: 'Lieferklauseln der Internationalen Handelskammer',
    art: 'norm',
    berufe: ['grosshandel', 'spedition'],
  },
  {
    id: 'uzk',
    kuerzel: 'UZK',
    titel: 'Unionszollkodex, VO (EU) 952/2013',
    art: 'gesetz',
    berufe: ['grosshandel', 'spedition'],
  },
  {
    id: 'awv',
    kuerzel: 'AWG / AWV',
    titel: 'Außenwirtschaftsgesetz und -verordnung',
    art: 'gesetz',
    berufe: ['grosshandel'],
  },
  {
    id: 'ustg-par-4-nr-1',
    kuerzel: 'UStG § 4 Nr. 1',
    titel: 'Innergemeinschaftliche Lieferung und Ausfuhrlieferung',
    art: 'gesetz',
    berufe: ['grosshandel'],
  },
  {
    id: 'era-600',
    kuerzel: 'ERA 600',
    titel: 'Einheitliche Richtlinien für Dokumenten-Akkreditive',
    art: 'norm',
    berufe: ['grosshandel'],
  },
  {
    id: 'atlas',
    kuerzel: 'ATLAS',
    titel: 'Elektronisches Zollverfahren des Zolls',
    art: 'nachschlagewerk',
    berufe: ['grosshandel'],
  },
  {
    id: 'zoll-de',
    kuerzel: 'Zoll.de',
    titel: 'Portal der Zollverwaltung',
    art: 'nachschlagewerk',
    berufe: ['grosshandel'],
  },
  {
    id: 'lksg',
    kuerzel: 'LkSG',
    titel: 'Lieferkettensorgfaltspflichtengesetz',
    art: 'gesetz',
    berufe: ['grosshandel'],
  },
  {
    id: 'ao-industriekaufleute-2024',
    kuerzel: 'Ausbildungsordnung',
    titel: 'Verordnung über die Berufsausbildung zum Industriekaufmann (Neuordnung 2024)',
    art: 'vorgabe',
    berufe: ['industrie'],
    standard: true,
    prompt: 'Verordnung über die Berufsausbildung zum Industriekaufmann (Neuordnung 2024)',
  },
  {
    // Nachgetragen bei der Übernahme in die Anwendung: Als einziger Beruf
    // hatte IK keinen eigenen Rahmenlehrplan-Eintrag.
    id: 'rahmenlehrplan-industrie',
    kuerzel: 'Rahmenlehrplan',
    titel: 'Lernfelder nach der Neuordnung 2024',
    art: 'vorgabe',
    berufe: ['industrie'],
    standard: true,
    prompt: 'Rahmenlehrplan der KMK für Industriekaufleute (Neuordnung 2024)',
  },
  {
    id: 'gwb',
    kuerzel: 'GWB',
    titel: 'Gesetz gegen Wettbewerbsbeschränkungen',
    art: 'gesetz',
    berufe: ['industrie'],
  },
  {
    id: 'hgb-par-238-342e',
    kuerzel: 'HGB §§ 238–342e',
    titel: 'Handelsbilanzrecht',
    art: 'gesetz',
    berufe: ['industrie'],
  },
  {
    id: 'kstg',
    kuerzel: 'KStG',
    titel: 'Körperschaftsteuergesetz',
    art: 'gesetz',
    berufe: ['industrie'],
  },
  {
    id: 'gewstg',
    kuerzel: 'GewStG',
    titel: 'Gewerbesteuergesetz',
    art: 'gesetz',
    berufe: ['industrie'],
  },
  {
    id: 'betrvg-par-87-ff',
    kuerzel: 'BetrVG §§ 87 ff.',
    titel: 'Mitbestimmung in sozialen Angelegenheiten',
    art: 'gesetz',
    berufe: ['industrie'],
  },
  {
    id: 'refa',
    kuerzel: 'REFA',
    titel: 'REFA-Methodenlehre',
    art: 'nachschlagewerk',
    berufe: ['industrie'],
  },
  {
    id: 'din-en-iso-9001',
    kuerzel: 'DIN EN ISO 9001',
    titel: 'Qualitätsmanagementsysteme',
    art: 'norm',
    berufe: ['industrie'],
  },
  {
    id: 'ifrs',
    kuerzel: 'IFRS',
    titel: 'International Financial Reporting Standards',
    art: 'norm',
    berufe: ['industrie'],
  },
  {
    id: 'ao-immobilienkaufleute',
    kuerzel: 'Ausbildungsordnung',
    titel: 'Verordnung über die Berufsausbildung zum Immobilienkaufmann',
    art: 'vorgabe',
    berufe: ['immobilien'],
    standard: true,
    prompt: 'Verordnung über die Berufsausbildung zum Immobilienkaufmann',
  },
  {
    id: 'rahmenlehrplan-imk',
    kuerzel: 'Rahmenlehrplan',
    titel: 'Zwölf Lernfelder',
    art: 'vorgabe',
    berufe: ['immobilien'],
    standard: true,
    prompt: 'Rahmenlehrplan der KMK für Immobilienkaufleute',
  },
  {
    id: 'vob-b-und-hoai',
    kuerzel: 'VOB/B und HOAI',
    titel: 'Bauvertrag und Architektenhonorar',
    art: 'gesetz',
    berufe: ['immobilien'],
  },
  {
    id: 'bgb-par-1113-ff',
    kuerzel: 'BGB §§ 1113 ff.',
    titel: 'Hypothek und Grundschuld',
    art: 'gesetz',
    berufe: ['immobilien'],
  },
  {
    id: 'gewerbemietrecht',
    kuerzel: 'BGB § 578',
    titel: 'Miete über Geschäftsräume',
    art: 'gesetz',
    berufe: ['immobilien'],
    prompt: 'BGB § 578 (Mietverhältnisse über Grundstücke und Räume)',
  },
  {
    id: 'bgb-par-535-580a',
    kuerzel: 'BGB §§ 535–580a',
    titel: 'Mietrecht',
    art: 'gesetz',
    berufe: ['immobilien'],
  },
  {
    id: 'weg',
    kuerzel: 'WEG',
    titel: 'Wohnungseigentumsgesetz',
    art: 'gesetz',
    berufe: ['immobilien'],
  },
  {
    id: 'betrkv',
    kuerzel: 'BetrKV',
    titel: 'Betriebskostenverordnung',
    art: 'gesetz',
    berufe: ['immobilien'],
  },
  {
    id: 'heizkostenv',
    kuerzel: 'HeizkostenV',
    titel: 'Heizkostenverordnung',
    art: 'gesetz',
    berufe: ['immobilien'],
  },
  {
    id: 'mabv',
    kuerzel: 'MaBV',
    titel: 'Makler- und Bauträgerverordnung',
    art: 'gesetz',
    berufe: ['immobilien'],
  },
  {
    id: 'gewo-par-34c',
    kuerzel: 'GewO § 34c',
    titel: 'Erlaubnis für Makler, Verwalter und Bauträger',
    art: 'gesetz',
    berufe: ['immobilien'],
  },
  {
    id: 'wovermrg',
    kuerzel: 'WoVermRG',
    titel: 'Wohnungsvermittlungsgesetz',
    art: 'gesetz',
    berufe: ['immobilien'],
  },
  {
    id: 'gbo',
    kuerzel: 'GBO',
    titel: 'Grundbuchordnung',
    art: 'gesetz',
    berufe: ['immobilien'],
  },
  {
    id: 'baugb',
    kuerzel: 'BauGB',
    titel: 'Baugesetzbuch',
    art: 'gesetz',
    berufe: ['immobilien'],
  },
  {
    id: 'bauo-nrw',
    kuerzel: 'BauO NRW',
    titel: 'Landesbauordnung Nordrhein-Westfalen',
    art: 'gesetz',
    berufe: ['immobilien'],
  },
  {
    id: 'geg',
    kuerzel: 'GEG',
    titel: 'Gebäudeenergiegesetz',
    art: 'gesetz',
    berufe: ['immobilien'],
  },
  {
    id: 'immowertv',
    kuerzel: 'ImmoWertV',
    titel: 'Immobilienwertermittlungsverordnung',
    art: 'gesetz',
    berufe: ['immobilien'],
  },
  {
    id: 'grestg-grstg',
    kuerzel: 'GrEStG / GrStG',
    titel: 'Grunderwerbsteuer und Grundsteuer',
    art: 'gesetz',
    berufe: ['immobilien', 'steuerfach'],
  },
  {
    id: 'wofg-wobindg',
    kuerzel: 'WoFG / WoBindG',
    titel: 'Wohnraumförderung und Belegungsbindung',
    art: 'gesetz',
    berufe: ['immobilien'],
  },
  {
    id: 'erbbaurg',
    kuerzel: 'ErbbauRG',
    titel: 'Erbbaurechtsgesetz',
    art: 'gesetz',
    berufe: ['immobilien'],
  },
  {
    id: 'schmidt-futterer',
    kuerzel: 'Schmidt-Futterer',
    titel: 'Mietrecht, Kommentar',
    art: 'nachschlagewerk',
    berufe: ['immobilien'],
  },
  {
    id: 'mietspiegel',
    kuerzel: 'Mietspiegel',
    titel: 'Örtlicher Mietspiegel',
    art: 'daten',
    berufe: ['immobilien'],
    prompt: 'örtlicher Mietspiegel',
  },
  {
    id: 'bgh-viii-zr-v-zr',
    kuerzel: 'BGH',
    titel: 'Mietrecht und Wohnungseigentum',
    art: 'rechtsprechung',
    berufe: ['immobilien'],
    prompt: 'Rechtsprechung des BGH (VIII. Zivilsenat: Miete; V. Zivilsenat: Wohnungseigentum)',
  },
  {
    id: 'ao-bueromanagement',
    kuerzel: 'Ausbildungsordnung',
    titel: 'Verordnung über die Berufsausbildung zum Kaufmann für Büromanagement',
    art: 'vorgabe',
    berufe: ['bueromanagement'],
    standard: true,
    prompt: 'Verordnung über die Berufsausbildung zum Kaufmann für Büromanagement',
  },
  {
    id: 'rahmenlehrplan-kbm',
    kuerzel: 'Rahmenlehrplan',
    titel: 'Dreizehn Lernfelder, 880 Stunden',
    art: 'vorgabe',
    berufe: ['bueromanagement'],
    standard: true,
    prompt: 'Rahmenlehrplan der KMK für Kaufleute für Büromanagement',
  },
  {
    id: 'reisekostenrecht',
    kuerzel: 'Reisekostenrecht',
    titel: 'Verpflegungspauschalen, Fahrtkosten, Übernachtung',
    art: 'gesetz',
    berufe: ['bueromanagement'],
    prompt: '§ 9 EStG und Lohnsteuer-Richtlinien (Reisekosten)',
  },
  {
    id: 'prozessdarstellung',
    kuerzel: 'DIN 69901 / BPMN',
    titel: 'Ereignisgesteuerte Prozesskette, BPMN, DIN 69901',
    art: 'norm',
    berufe: ['bueromanagement'],
    prompt: 'DIN 69901 (Projektmanagement) und BPMN (Prozessmodellierung)',
  },
  {
    id: 'din-5008',
    kuerzel: 'DIN 5008',
    titel: 'Schreib- und Gestaltungsregeln für die Textverarbeitung',
    art: 'norm',
    berufe: ['bueromanagement'],
  },
  {
    id: 'din-676',
    kuerzel: 'DIN 676',
    titel: 'Geschäftsbrief — Gestaltung',
    art: 'norm',
    berufe: ['bueromanagement'],
  },
  {
    id: 'ustg-par-14',
    kuerzel: 'UStG § 14',
    titel: 'Pflichtangaben einer Rechnung',
    art: 'gesetz',
    berufe: ['bueromanagement'],
  },
  {
    id: 'bdsg-par-26',
    kuerzel: 'BDSG § 26',
    titel: 'Beschäftigtendatenschutz',
    art: 'gesetz',
    berufe: ['bueromanagement', 'personaldienstleistung'],
  },
  {
    id: 'uvgo-vgv',
    kuerzel: 'UVgO / VgV',
    titel: 'Vergaberecht',
    art: 'gesetz',
    berufe: ['bueromanagement'],
  },
  {
    id: 'ao-e-commerce',
    kuerzel: 'Ausbildungsordnung',
    titel: 'Verordnung über die Berufsausbildung zum Kaufmann im E-Commerce',
    art: 'vorgabe',
    berufe: ['ecommerce'],
    standard: true,
    prompt: 'Verordnung über die Berufsausbildung zum Kaufmann im E-Commerce',
  },
  {
    id: 'rahmenlehrplan-kec',
    kuerzel: 'Rahmenlehrplan',
    titel: 'Zwölf Lernfelder',
    art: 'vorgabe',
    berufe: ['ecommerce'],
    standard: true,
    prompt: 'Rahmenlehrplan der KMK für Kaufleute im E-Commerce',
  },
  {
    id: 'zag-und-psd2',
    kuerzel: 'ZAG und PSD2',
    titel: 'Zahlungsdiensteaufsichtsgesetz, starke Kundenauthentifizierung',
    art: 'gesetz',
    berufe: ['ecommerce'],
  },
  {
    id: 'ustg-par-18j',
    kuerzel: 'UStG § 18j',
    titel: 'One-Stop-Shop beim Fernverkauf in der EU',
    art: 'gesetz',
    berufe: ['ecommerce'],
  },
  {
    id: 'egbgb-art-246a',
    kuerzel: 'EGBGB Art. 246a',
    titel: 'Informationspflichten bei Fernabsatzverträgen',
    art: 'gesetz',
    berufe: ['ecommerce'],
  },
  {
    id: 'ddg',
    kuerzel: 'DDG',
    titel: 'Digitale-Dienste-Gesetz',
    art: 'gesetz',
    berufe: ['ecommerce'],
  },
  {
    id: 'tdddg-par-25',
    kuerzel: 'TDDDG § 25',
    titel: 'Einwilligung für Cookies und Endgerätezugriff',
    art: 'gesetz',
    berufe: ['ecommerce'],
  },
  {
    id: 'dsa',
    kuerzel: 'DSA',
    titel: 'EU-Verordnung über digitale Dienste 2022/2065',
    art: 'gesetz',
    berufe: ['ecommerce'],
  },
  {
    id: 'p2b-vo',
    kuerzel: 'P2B-VO',
    titel: 'EU-Verordnung 2019/1150 für Online-Vermittlungsdienste',
    art: 'gesetz',
    berufe: ['ecommerce'],
  },
  {
    id: 'uwg-par-5-5b-7',
    kuerzel: 'UWG §§ 5, 5b, 7',
    titel: 'Irreführung, Bewertungen, E-Mail-Werbung',
    art: 'gesetz',
    berufe: ['ecommerce'],
  },
  {
    id: 'urhg-markeng',
    kuerzel: 'UrhG / MarkenG',
    titel: 'Produktbilder, Texte, Marken Dritter',
    art: 'gesetz',
    berufe: ['ecommerce'],
  },
  {
    id: 'geoblocking-vo',
    kuerzel: 'Geoblocking-VO',
    titel: 'EU-Verordnung 2018/302',
    art: 'gesetz',
    berufe: ['ecommerce'],
  },
  {
    id: 'verpackg-elektrog-battg',
    kuerzel: 'VerpackG / ElektroG / BattG',
    titel: 'Rücknahme- und Registrierungspflichten',
    art: 'gesetz',
    berufe: ['ecommerce'],
  },
  {
    id: 'vsbg',
    kuerzel: 'VSBG',
    titel: 'Verbraucherstreitbeilegungsgesetz',
    art: 'gesetz',
    berufe: ['ecommerce'],
  },
  {
    id: 'eugh-planet49',
    kuerzel: 'EuGH C-673/17',
    titel: 'Cookie-Einwilligung, C-673/17',
    art: 'rechtsprechung',
    berufe: ['ecommerce'],
    prompt: 'EuGH, C-673/17 (Planet49), zur Cookie-Einwilligung',
  },
  {
    id: 'bevh',
    kuerzel: 'Bevh',
    titel: 'Bundesverband E-Commerce und Versandhandel',
    art: 'daten',
    berufe: ['ecommerce'],
  },
  {
    id: 'ao-gesundheitswesen',
    kuerzel: 'Ausbildungsordnung',
    titel: 'Verordnung über die Berufsausbildung zum Kaufmann im Gesundheitswesen',
    art: 'vorgabe',
    berufe: ['gesundheit'],
    standard: true,
    prompt: 'Verordnung über die Berufsausbildung zum Kaufmann im Gesundheitswesen',
  },
  {
    id: 'rahmenlehrplan-kig',
    kuerzel: 'Rahmenlehrplan',
    titel: 'Elf Lernfelder in drei Fächern',
    art: 'vorgabe',
    berufe: ['gesundheit'],
    standard: true,
    prompt: 'Rahmenlehrplan der KMK für Kaufleute im Gesundheitswesen',
  },
  {
    id: 'qualitaetsmanagement',
    kuerzel: 'Qualitätsmanagement',
    titel: 'QM-Richtlinie des G-BA, DIN EN ISO 9001, KTQ',
    art: 'norm',
    berufe: ['gesundheit'],
  },
  {
    id: 'sgb5',
    kuerzel: 'SGB V',
    titel: 'Gesetzliche Krankenversicherung',
    art: 'gesetz',
    berufe: ['gesundheit'],
  },
  {
    id: 'sgb11',
    kuerzel: 'SGB XI',
    titel: 'Soziale Pflegeversicherung',
    art: 'gesetz',
    berufe: ['gesundheit'],
  },
  {
    id: 'sgb-ix',
    kuerzel: 'SGB IX',
    titel: 'Rehabilitation und Teilhabe',
    art: 'gesetz',
    berufe: ['gesundheit'],
  },
  {
    id: 'sgb-vii',
    kuerzel: 'SGB VII',
    titel: 'Gesetzliche Unfallversicherung',
    art: 'gesetz',
    berufe: ['gesundheit'],
  },
  {
    id: 'khg-khentgg',
    kuerzel: 'KHG / KHEntgG',
    titel: 'Krankenhausfinanzierung und Entgelte',
    art: 'gesetz',
    berufe: ['gesundheit'],
  },
  {
    id: 'drg-katalog',
    kuerzel: 'DRG-Katalog',
    titel: 'Fallpauschalenkatalog des InEK',
    art: 'norm',
    berufe: ['gesundheit'],
  },
  {
    id: 'icd-10-gm-ops',
    kuerzel: 'ICD-10-GM / OPS',
    titel: 'Klassifikationen des BfArM',
    art: 'norm',
    berufe: ['gesundheit'],
  },
  {
    id: 'ebm-goae',
    kuerzel: 'EBM / GOÄ',
    titel: 'Vergütung ambulanter Leistungen',
    art: 'norm',
    berufe: ['gesundheit'],
  },
  {
    id: 'bgb-par-630a-ff',
    kuerzel: 'BGB §§ 630a ff.',
    titel: 'Behandlungsvertrag',
    art: 'gesetz',
    berufe: ['gesundheit'],
  },
  {
    id: 'stgb-par-203',
    kuerzel: 'StGB § 203',
    titel: 'Verletzung von Privatgeheimnissen',
    art: 'gesetz',
    berufe: ['gesundheit'],
  },
  {
    id: 'dsgvo-art-9',
    kuerzel: 'DSGVO Art. 9',
    titel: 'Gesundheitsdaten als besondere Kategorie',
    art: 'gesetz',
    berufe: ['gesundheit'],
  },
  {
    id: 'ifsg',
    kuerzel: 'IfSG',
    titel: 'Infektionsschutzgesetz',
    art: 'gesetz',
    berufe: ['gesundheit'],
  },
  {
    id: 'medhygvo-nrw',
    kuerzel: 'MedHygVO NRW',
    titel: 'Verordnung über die Hygiene in medizinischen Einrichtungen',
    art: 'gesetz',
    berufe: ['gesundheit'],
  },
  {
    id: 'hwg',
    kuerzel: 'HWG',
    titel: 'Heilmittelwerbegesetz',
    art: 'gesetz',
    berufe: ['gesundheit'],
  },
  {
    id: 'amg-mpdg-apog',
    kuerzel: 'AMG / MPDG / ApoG',
    titel: 'Arzneimittel, Medizinprodukte, Apotheken',
    art: 'gesetz',
    berufe: ['gesundheit'],
  },
  {
    id: 'g-ba',
    kuerzel: 'G-BA',
    titel: 'Richtlinien des Gemeinsamen Bundesausschusses',
    art: 'nachschlagewerk',
    berufe: ['gesundheit'],
  },
  {
    id: 'gkv-spitzenverband',
    kuerzel: 'GKV-Spitzenverband',
    titel: 'Kennzahlen und Vereinbarungen',
    art: 'daten',
    berufe: ['gesundheit'],
  },
  {
    id: 'bsg',
    kuerzel: 'BSG',
    titel: 'Bundessozialgericht',
    art: 'rechtsprechung',
    berufe: ['gesundheit'],
  },
  {
    id: 'ao-personaldienstleistung',
    kuerzel: 'Ausbildungsordnung',
    titel: 'Verordnung über die Berufsausbildung zum Personaldienstleistungskaufmann',
    art: 'vorgabe',
    berufe: ['personaldienstleistung'],
    standard: true,
    prompt: 'Verordnung über die Berufsausbildung zum Personaldienstleistungskaufmann',
  },
  {
    id: 'rahmenlehrplan-pdk',
    kuerzel: 'Rahmenlehrplan',
    titel: 'Zwölf Lernfelder, 880 Stunden',
    art: 'vorgabe',
    berufe: ['personaldienstleistung'],
    standard: true,
    prompt: 'Rahmenlehrplan der KMK für Personaldienstleistungskaufleute',
  },
  {
    id: 'abgrenzung-der-vertragsarten',
    kuerzel: '§ 7a SGB IV',
    titel: 'Statusfeststellung — Abgrenzung von Arbeitnehmerüberlassung, Werk- und Dienstvertrag',
    art: 'gesetz',
    berufe: ['personaldienstleistung'],
    prompt: '§ 7a SGB IV (Statusfeststellung) zur Abgrenzung von Arbeitnehmerüberlassung, Werk- und Dienstvertrag',
  },
  {
    id: 'auegg',
    kuerzel: 'AÜG',
    titel: 'Arbeitnehmerüberlassungsgesetz',
    art: 'gesetz',
    berufe: ['personaldienstleistung'],
  },
  {
    id: 'tarifwerk-zeitarbeit',
    kuerzel: 'Tarifwerk Zeitarbeit',
    titel: 'BAP/iGZ-DGB-Tarifverträge',
    art: 'norm',
    berufe: ['personaldienstleistung'],
    prompt: 'Tarifverträge der Zeitarbeit (BAP/iGZ–DGB)',
  },
  {
    id: 'aentg',
    kuerzel: 'AEntG',
    titel: 'Arbeitnehmer-Entsendegesetz',
    art: 'gesetz',
    berufe: ['personaldienstleistung'],
  },
  {
    id: 'sgb-iii',
    kuerzel: 'SGB III',
    titel: 'Arbeitsförderung',
    art: 'gesetz',
    berufe: ['personaldienstleistung'],
  },
  {
    id: 'sgb-iv',
    kuerzel: 'SGB IV',
    titel: 'Gemeinsame Vorschriften der Sozialversicherung',
    art: 'gesetz',
    berufe: ['personaldienstleistung'],
  },
  {
    id: 'schwarzarbg',
    kuerzel: 'SchwarzArbG',
    titel: 'Schwarzarbeitsbekämpfungsgesetz',
    art: 'gesetz',
    berufe: ['personaldienstleistung'],
  },
  {
    id: 'betrvg-par-14',
    kuerzel: 'BetrVG § 14',
    titel: 'Wahlrecht überlassener Arbeitnehmer',
    art: 'gesetz',
    berufe: ['personaldienstleistung'],
  },
  {
    id: 'bag-zur-zeitarbeit',
    kuerzel: 'BAG',
    titel: 'Equal Pay und Überlassungshöchstdauer',
    art: 'rechtsprechung',
    berufe: ['personaldienstleistung'],
    prompt: 'Rechtsprechung des BAG zur Arbeitnehmerüberlassung',
  },
  {
    id: 'ba-statistik',
    kuerzel: 'BA-Statistik',
    titel: 'Bundesagentur für Arbeit',
    art: 'daten',
    berufe: ['personaldienstleistung'],
  },
  {
    id: 'ao-steuerfachangestellte',
    kuerzel: 'Ausbildungsordnung',
    titel: 'Verordnung über die Berufsausbildung zum Steuerfachangestellten',
    art: 'vorgabe',
    berufe: ['steuerfach'],
    standard: true,
    prompt: 'Verordnung über die Berufsausbildung zum Steuerfachangestellten',
  },
  {
    id: 'rahmenlehrplan-sfa-2022',
    kuerzel: 'Rahmenlehrplan',
    titel: 'Zwölf Lernfelder, KMK-Beschluss vom 10.06.2022',
    art: 'vorgabe',
    berufe: ['steuerfach'],
    standard: true,
    prompt: 'Rahmenlehrplan der KMK für Steuerfachangestellte',
  },
  {
    id: 'lohn-und-gehaltsabrechnung',
    kuerzel: 'LStR',
    titel: 'Lohnsteuerrichtlinien, Sozialversicherung, DEÜV',
    art: 'nachschlagewerk',
    berufe: ['steuerfach'],
    prompt: 'Lohnsteuer-Richtlinien (LStR)',
  },
  {
    id: 'estg-mit-estdv-estr-esth',
    kuerzel: 'EStG mit EStDV, EStR, EStH',
    titel: 'Einkommensteuer samt Durchführungsverordnung und Richtlinien',
    art: 'gesetz',
    berufe: ['steuerfach'],
  },
  {
    id: 'ustg-mit-ustdv-ustae',
    kuerzel: 'UStG mit UStDV, UStAE',
    titel: 'Umsatzsteuer samt Anwendungserlass',
    art: 'gesetz',
    berufe: ['steuerfach'],
  },
  {
    id: 'kstg-gewstg',
    kuerzel: 'KStG / GewStG',
    titel: 'Körperschaft- und Gewerbesteuer',
    art: 'gesetz',
    berufe: ['steuerfach'],
  },
  {
    id: 'erbstg-bewg',
    kuerzel: 'ErbStG / BewG',
    titel: 'Erbschaftsteuer und Bewertungsgesetz',
    art: 'gesetz',
    berufe: ['steuerfach'],
  },
  {
    id: 'stberg-bostb-stbvv',
    kuerzel: 'StBerG / BOStB / StBVV',
    titel: 'Berufsrecht der Steuerberater',
    art: 'gesetz',
    berufe: ['steuerfach'],
  },
  {
    id: 'hgb-par-238-ff',
    kuerzel: 'HGB §§ 238 ff.',
    titel: 'Handelsbilanz als Grundlage der Steuerbilanz',
    art: 'gesetz',
    berufe: ['steuerfach'],
  },
  {
    id: 'fgo',
    kuerzel: 'FGO',
    titel: 'Finanzgerichtsordnung',
    art: 'gesetz',
    berufe: ['steuerfach'],
  },
  {
    id: 'bmf-schreiben',
    kuerzel: 'BMF-Schreiben',
    titel: 'Verwaltungsanweisungen des Bundesfinanzministeriums',
    art: 'nachschlagewerk',
    berufe: ['steuerfach'],
  },
  {
    id: 'bfh',
    kuerzel: 'BFH',
    titel: 'Bundesfinanzhof',
    art: 'rechtsprechung',
    berufe: ['steuerfach'],
  },
  {
    id: 'schmidt-estg',
    kuerzel: 'Schmidt, EStG',
    titel: 'Kommentar zum Einkommensteuergesetz',
    art: 'nachschlagewerk',
    berufe: ['steuerfach'],
  },
  {
    id: 'datev',
    kuerzel: 'DATEV',
    titel: 'Dokumentation und Hilfen zur Kanzleisoftware',
    art: 'nachschlagewerk',
    berufe: ['steuerfach'],
  },
  {
    id: 'dws-steuerberaterkammer',
    kuerzel: 'Steuerberaterkammer',
    titel: 'Prüfungsmaterial der Kammer',
    art: 'vorgabe',
    berufe: ['steuerfach'],
    prompt: 'Prüfungsaufgaben der Steuerberaterkammern',
  },
  {
    id: 'ao-spedition',
    kuerzel: 'Ausbildungsordnung',
    titel: 'Verordnung über die Berufsausbildung zum Kaufmann für Spedition und Logistikdienstleistung',
    art: 'vorgabe',
    berufe: ['spedition'],
    standard: true,
    prompt: 'Verordnung über die Berufsausbildung zum Kaufmann für Spedition und Logistikdienstleistung',
  },
  {
    id: 'rahmenlehrplan-sl',
    kuerzel: 'Rahmenlehrplan',
    titel: 'Fünfzehn Lernfelder, 880 Stunden',
    art: 'vorgabe',
    berufe: ['spedition'],
    standard: true,
    prompt: 'Rahmenlehrplan der KMK für Kaufleute für Spedition und Logistikdienstleistungen',
  },
  {
    id: 'bfstrmg',
    kuerzel: 'BFStrMG',
    titel: 'Bundesfernstraßenmautgesetz',
    art: 'gesetz',
    berufe: ['spedition'],
  },
  {
    id: 'hgb-par-407-475h',
    kuerzel: 'HGB §§ 407–475h',
    titel: 'Fracht-, Speditions- und Lagergeschäft',
    art: 'gesetz',
    berufe: ['spedition'],
  },
  {
    id: 'adsp',
    kuerzel: 'ADSp 2017',
    titel: 'Allgemeine Deutsche Spediteurbedingungen',
    art: 'norm',
    berufe: ['spedition'],
  },
  {
    id: 'cmr',
    kuerzel: 'CMR',
    titel: 'Internationaler Straßengüterverkehr',
    art: 'gesetz',
    berufe: ['spedition'],
  },
  {
    id: 'cim-cotif',
    kuerzel: 'CIM / COTIF',
    titel: 'Internationaler Eisenbahnverkehr',
    art: 'gesetz',
    berufe: ['spedition'],
  },
  {
    id: 'montrealer-uebereinkommen',
    kuerzel: 'Montrealer Übereinkommen',
    titel: 'Luftfrachtbeförderung',
    art: 'gesetz',
    berufe: ['spedition'],
  },
  {
    id: 'seefracht',
    kuerzel: 'HGB §§ 476 ff.',
    titel: 'Seehandelsrecht, Konnossement',
    art: 'gesetz',
    berufe: ['spedition'],
    prompt: 'Seehandelsrecht des HGB (§§ 476 ff.)',
  },
  {
    id: 'guekg',
    kuerzel: 'GüKG',
    titel: 'Güterkraftverkehrsgesetz',
    art: 'gesetz',
    berufe: ['spedition'],
  },
  {
    id: 'imdg-iata-dgr',
    kuerzel: 'IMDG / IATA-DGR',
    titel: 'Gefahrgut auf See und in der Luft',
    art: 'norm',
    berufe: ['spedition'],
  },
  {
    id: 'vvg-transportversicherung',
    kuerzel: 'VVG / Transportversicherung',
    titel: 'Versicherungsvertragsgesetz und DTV-Güterversicherung',
    art: 'gesetz',
    berufe: ['spedition'],
  },
  {
    id: 'stvo-par-22-vdi-2700',
    kuerzel: 'StVO § 22 / VDI 2700',
    titel: 'Ladungssicherung',
    art: 'gesetz',
    berufe: ['spedition'],
  },
  {
    id: 'dslv',
    kuerzel: 'DSLV',
    titel: 'Bundesverband Spedition und Logistik',
    art: 'daten',
    berufe: ['spedition'],
  },
];
